Expanded the people section
datavaluepeople/dvp-defining-docs pull request #41
Opened 2024-01-29 12:40 UTC by ajg54

Wanted to include the category of non-member and specify an explanatory example _journey_ with dvp whilst avoiding making it sounds like a fixed process.

2024-01-29 12:41 UTC, ajg54 commented
Hereby sharing an idea about updating the people page.

2024-01-30 11:54 UTC, DBCerigo commented
Nice oneeeeee :smile_cat: 

I think the two parts would be good contributions. I think the implementation would benefit from being a bit more concise if pos ala https://github.com/datavaluepeople/dvp-defining-docs?tab=readme-ov-file#contributing-to-this-repo

I think the grammatical fix/change to the Members bit is good, but not so sure about removing the bit about becoming a partner, I think that's pretty important, to show that all members always have the possibility of being a partner. 

I think best way to progress would be to break up the changes into different commits. This will make it easier to review and discuss and more likely and faster for it to get agreed and merged. Something like a commit for each of:
- grammar fix
- removing the bit about becoming partners
- paragraph on freelances
- paragraph on journey

2024-01-30 14:05 UTC, ajg54 commented
Thanks for taking a look. I recalled some discussion about whether there was an expectation that members _should_ eventually become partners, which was why I thought to move that line from the definition to the journey. Perhaps the easiest way is to move it back (i.e. leave it as it was before), then there are just three changes: grammar fix, non-members and journey. At the same time I can trim the language a little.

2024-01-31 07:22 UTC, DBCerigo commented
> recalled some discussion about whether there was an expectation that members _should_ eventually become partners, which was why I thought to move that line from the definition to the journey.

Ye you totally right. That would be nice to capture also. I guess it is like "hope for partners, but no pressure and no frets if not".

2024-02-03 14:14 UTC, ajg54 commented
OK, the changes should now be split up over three commits. I have made the changes more modest both in terms of word count and difference from the original. In the end I didn't change the part about becoming a partner as I thought that _hope_ already captured the intended vibe.

2024-02-05 10:49 UTC, DBCerigo requested changes
Yea looking better and much easier to review now split up :) 

Few comments, and also the formatting on line length isn't right on most of it. Having your editor auto-format text to do linebreaks up to a certain line-length is something well worth investing the time in!

2024-02-05 10:49 UTC, DBCerigo commented on people.md
> +  provide input to the direction and development of dvp, while slowly strengthening their
Approved.

2024-02-05 10:49 UTC, DBCerigo commented on people.md
> +There is a further category of _non-member_ or _freelancer_.
Suggestion: "There is a further category of people: _non-member_ or similarly _freelancer_."

2024-02-05 10:49 UTC, DBCerigo commented on people.md
> +An example _journey_ for a newcomer could be performing a well-defined task for dvp,
Suggestion: remove `_` from journey.

2024-02-05 10:49 UTC, DBCerigo commented on people.md
> +and if the relationship continues to grow may eventually become a partner.
Suggestion: "to grow they may eventually".

2025-01-16 15:13 UTC, ajg54 commented
Taking care of the marketing page, reminded me of this long-standing PR. Since it was quite old, I brought it up to date with `main` and have then implemented the suggested changes. If there is a different preferred way to do that, just let me know for next time.

2025-01-21 10:15 UTC, DBCerigo approved these changes
Good to go for me :) Nice one

2025-01-23 15:43 UTC, ajg54 commented
Thanks for looking again and the general feedback. Makes sense. Having the _commit clean-up_ at the end allows the reviewers to see the iterative changes, whereas doing it in my order was more of a 'take a look at it from scratch' approach.

2025-01-23 15:51 UTC, benjamincerigo approved these changes
Looks great. I think the commit clean up is not needed as, for me, the commits are there to show the history of changes. No harm if you do want to clean the commits up.

2025-01-23 16:00 UTC, merged